### ISSUE TITLE
(Rename and) upstream xapi packages

### ISSUE THREAD

**Issue by djs55** [xapi-project/opam-repo-dev#41]
- [x] camldm [ocaml/opam-repository#2681]
- [x] nbd [ocaml/opam-repository#2678]
- [x] xenctrl [ocaml/opam-repository#2682]
- [x] vhdlib [ocaml/opam-repository#2683]
- [x] netlink [ocaml/opam-repository#2695]
- [ ] remove forkexecd dependence from netdev
- [x] rename xcp to xapi-idl
- [x] rename xcp-inventory to xapi-inventory
- [x] rename xcp-networkd to xapi-networkd
- [x] rename xcp-rrdd to xapi-rrdd
- [x] rename message_switch to message-switch
- [x] rename xen-api-libs-transitional to xapi-libs-transitional
- [x] rename rrdd-plugin
- [x] rename xapi-rrd-transport to xapi-rrd-transport
- [x] rename squeezed to xapi-squeezed
- [x] rename tapctl to xapi-tapctl
- [x] rename netdev to xapi-netdev
- [x] rename xenopsd to xapi-xenopsd
- [x] rename xenops-cli to xapi-xenops-cli
- [x] rename xenops to xapi-xenops
